### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by NiviJah** [ph5x5/albion-minimap-overlay#6]
Traceback (most recent call last):
  File "albion-minimap-overlay.py", line 18, in <module>
  File "json\__init__.py", line 296, in load
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Invalid \escape: line 4 column 32 (char 98)
[9452] Failed to execute script albion-minimap-overlay

**Comment by NiviJah** [comment]
it was a JSON error, fixed
